# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 庞存洪
email: pangcunhong@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  MoHee © 2016 

#网站的根路径
baseurl: / # the subpath of your site, e.g. /blog
#BASE_PATH: /_posts
#字符编码
encoding: utf-8

#分页
#gems: [jekyll-paginate]
#the number of articles on each page
#paginate: 5
#页的路径 page2->page3->page4...
#paginate_path: "/post/page:num"


url: "http://yourdomain.com" # the base hostname & protocol for your site
facebook_username: Jhon_Pang
twitter_username: Jhon_Pang
github_username:  MoHee-PCH
sina_weibo: pangcunhong

# Build settings
markdown: kramdown
